CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    AGE NUMBER,
    LOAN_INTEREST NUMBER
);
SELECT table_name FROM user_tables WHERE table_name = 'CUSTOMERS';
DESC CUSTOMERS;
DROP TABLE CUSTOMERS;
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    AGE NUMBER,
    LOAN_INTEREST NUMBER
);
INSERT INTO CUSTOMERS VALUES (1, 65, 9.5);
INSERT INTO CUSTOMERS VALUES (2, 45, 10.0);
INSERT INTO CUSTOMERS VALUES (3, 70, 8.0);
INSERT INTO CUSTOMERS VALUES (4, 61, 7.5);
COMMIT;
SET SERVEROUTPUT ON;

DECLARE
    CURSOR cust_cursor IS
        SELECT CUSTOMER_ID, AGE, LOAN_INTEREST FROM CUSTOMERS;
BEGIN
    FOR cust_rec IN cust_cursor LOOP
        IF cust_rec.AGE > 60 THEN
            UPDATE CUSTOMERS
            SET LOAN_INTEREST = cust_rec.LOAN_INTEREST - 1
            WHERE CUSTOMER_ID = cust_rec.CUSTOMER_ID;

            DBMS_OUTPUT.PUT_LINE('1% discount applied to customer ID: ' || cust_rec.CUSTOMER_ID);
        END IF;
    END LOOP;

    COMMIT;
END;
/
